// IotTechStack.tsx
"use client";

import { motion } from "framer-motion";
import img1 from "../Images/Group (1).png"; // replace with your actual image paths
import img2 from "../Images/Group (1).png";

/* ---------- Data ---------- */
type TechCard = { title: string; desc: string; imgSrc?: string };

const topRow: TechCard[] = [
  {
    title: "Sensors and actuators",
    desc:
      "Sensors detect environmental changes (like temperature, light, motion), while actuators create physical outcomes (like moving a motor or valve). Together, they enable automation by collecting metrics to sense and respond to the real world—without human input.",
  },
  {
    title: "Connectivity technologies",
    desc:
      "To transmit IoT data from sensors and actuators to the cloud, different networks can be combined to balance range, power and bandwidth. These include Wi-Fi, Bluetooth, cellular (4G/5G), LPWAN (LoRa/NB-IoT), Zigbee, and LoRaWAN.",
  },
  {
    title: "Cloud computing",
    desc:
      "The cloud is where the vast amount of data is processed and analyzed. Cloud platforms provide scalable storage, data pipelines, and orchestration with AI/ML services so information can move from devices to apps. Some data stays at the edge for fast decisions; the cloud can aggregate and deploy IoT applications.",
  },
];

const bottomRow: TechCard[] = [
  {
    title: "Big data analytics",
    desc:
      "To make sense of the vast amounts of data generated by IoT devices, businesses rely on data engineering and tools to extract insights from at-scale telemetry. This includes predictive/prescriptive models, feature stores, stream processing, and robust analytics pipelines.",
    imgSrc: img1,
  },
  {
    title: "Security and privacy technologies",
    desc:
      "As IoT deployments become widespread, IoT security and privacy become increasingly important. Techniques such as encryption, secure device identity and attestation, network segmentation, zero-trust access and device hardening help protect your systems and customers.",
    imgSrc: img2,
  },
];

/* ---------- Animations ---------- */
const container = {
  hidden: { opacity: 0, y: 10 },
  show: {
    opacity: 1,
    y: 0,
    transition: { staggerChildren: 0.12, delayChildren: 0.06 },
  },
};
const item = {
  hidden: { opacity: 0, y: 14, scale: 0.98 },
  show: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: { type: "spring", stiffness: 140, damping: 18 },
  },
};

/* ---------- Card (purple-outline + optional image) ---------- */
function GlowCard({ title, desc, imgSrc }: TechCard) {
  return (
    <motion.div
      variants={item}
      whileHover={{
        y: -3,
        boxShadow:
          "0 24px 60px -22px rgba(0,0,0,.55), 0 0 0 1px rgba(167,139,250,.16)",
      }}
      className="
        relative p-5 sm:p-6 text-white min-h-[176px] h-full
        bg-[linear-gradient(180deg,#0E1016_0%,#090B11_100%)]
        [border-image:linear-gradient(180deg,#1E46BC_0%,#8229AB_100%)_1]
        border-[2px]
        rounded-3xl overflow-hidden
      "
    >
      {/* Optional image (top-centered) */}
     

      <h3 className="text-[15px] sm:text-[22px] font-semibold text-center">
        {title}
      </h3>
      <p className="mt-2 text-[16px] leading-6 text-[#C9CBD4] text-center">
        {desc}
      </p>
       {imgSrc && (
        <div className="w-full flex justify-center mt-3">
          <img
            src={imgSrc}
            alt={title}
            className="w-[99px] h-[90px] object-contain rounded-xl"
          />
        </div>
      )}
    </motion.div>
  );
}

/* ---------- Section ---------- */
export default function IotTechStack() {
  return (
    <section className="text-white px-4 sm:px-8 lg:px-12 py-10 sm:py-14">
      <div className="mx-auto max-w-7xl relative p-6 sm:p-8 lg:p-10">
        {/* Heading */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          className="text-right mb-7 sm:mb-8"
        >
          <h2 className="text-[26px] sm:text-[34px] lg:text-[40px] font-semibold leading-tight">
            The technologies that make{" "}
            <span className="bg-[radial-gradient(425.56%_425.56%_at_50%_50%,_#8076F4_0%,_#FFFFFF_9.96%)] bg-clip-text text-transparent">
              <br /> IoT
            </span>{" "}
            possible
          </h2>
          <p className="mt-3 text-[14px] sm:text-[15px] text-[#B7BAC3]">
            Several technologies come together to make IoT possible.
          </p>
        </motion.div>

        {/* Top row */}
        <motion.div
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: "-110px" }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 sm:gap-6 items-stretch"
        >
          {topRow.map((c) => (
            <GlowCard key={c.title} {...c} />
          ))}
        </motion.div>

        {/* Bottom row (with images) */}
        <br />
        <motion.div
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: "-110px" }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-5 sm:gap-6 items-stretch"
        >
          {bottomRow.map((c) => (
            <GlowCard key={c.title} {...c} />
          ))}
        </motion.div>
      </div>
    </section>
  );
}
